### PR TITLE
docs: Add `@scalar/hono-api-reference` to the OpenAPI guide

### PR DESCRIPTION
**Pull request by hanspagel**
This PR adds `@scalar/hono-api-reference` as an alternative to the OpenAPI guide.

Looking forward to your feedback on this!

In love with Hono! ❤️‍🔥

### CODE REVIEW

**Comment by hanspagel** [comment]
Maybe it’s too prominent, though. Let me know If I should make it more clear it’s a community middleware or whatever. I’d love to iterate on it! ✌️

**Comment by hanspagel** [comment]
Hey, I saw you removed it from the website and just point to the README. 

Just wanted to say I think it’s great to have a dedicated guide on the website (even if it doesn’t mention our API reference 😅). I’ve written a few hundred pages of tech docs for my packages already. If you’d like me to write a guide on Zod OpenAPI Hono for the website, you’ll find my contact in the GitHub profile: https://github.com/hanspagel I’d love to contribute this. ✌️

Anyway, closing this here. Thanks, @yusukebe!

**Comment by yusukebe** [comment]
Hi @hanspagel ! Sorry for confusing.

We moved the content to **Snippets** https://hono.dev/snippets/top .

So you can add a `Scalar API Reference` page to the "Integration".

cc: @sor4chi

**Comment by hanspagel** [comment]
Still interested, but closing this one for now. ✌️

**Pull request closed without merging**
