### PR TITLE
docs: Add Jwt Utility 

### PR DESCRIPTION
**Pull request by NicoPlyley**
# Description

This pull request adds comprehensive documentation for the util/jwt module. 
The JWT docs includes information on:
- Import
- Sign
- Verify
- Decode
- Payload Validation
- Custom Error Types
- Supported AlgorithmTypes

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @NicoPlyley 

Please wait. We don't provide "utilities" in `utils/*` for the users officially, because these are internal-use only. But the JWT helper will be available in next version: https://github.com/honojs/hono/pull/1472

Duplicated: https://github.com/honojs/website/pull/96

**Comment by NicoPlyley** [comment]
Yes @yusukebe I noticed that after I submitted the PR. If you want to create branch for the next version, I can update and send a PR there instead

**Comment by yusukebe** [comment]
Hi @NicoPlyley 

I have rewritten it as helper. I will merge it for now. If there is anything wrong, I would appreciate it if you could make a PR! Thanks!

**Comment by julianpoma** [comment]
Amazing documentation 👏🏻

**Pull request merged**
