### PR TITLE
docs: for punycode

### PR DESCRIPTION
**Pull request by EdamAme-x**

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @EdamAme-x 

Please create a separate page!

**Comment by EdamAme-x** [comment]
sorry, what should i do?
Should I create this as a single page?

**Comment by yusukebe** [comment]
@EdamAme-x 

I think you can create a page like this: https://hono.dev/snippets/file-upload

**Comment by EdamAme-x** [comment]
understood.
thanks.

**Pull request closed without merging**
