### PR TITLE
docs: add cloudflare queue snippets

### PR DESCRIPTION
**Pull request by sor4chi**

### CODE REVIEW

**Comment by sor4chi** [comment]
https://github.com/honojs/examples/issues/98

**Comment by yusukebe** [comment]
Please add a short description and a `wrangler.toml` example.

**Comment by yusukebe** [comment]
@sor4chi 

Is this ready to review?

**Comment by sor4chi** [comment]
yes

**Comment by sor4chi** [comment]
Wait, I thought I should write the file name. sry

**Comment by sor4chi** [comment]
@yusukebe I'm ready!

**Comment by yusukebe** [comment]
Cooool! Let's go with this.

**Pull request merged**
