### PR TITLE
feat: add CBOR response example

### PR DESCRIPTION
**Pull request by 3w36zj6**
cf. https://github.com/honojs/hono/issues/3648

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @3w36zj6 

Thank you for the PR. I think `docs/api/context.md` is not a proper place for the CBOR description because that place should show minimal information though it's an example for using `setRenderer`/`c.renderer`.

So my suggestion is to add it to `examples` section: https://hono.dev/examples/

CleanShot 2024-11-16 at 04 38 38@2x

**Comment by 3w36zj6** [comment]
I have moved the content to the example.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@3w36zj6 

Awesome! I'll merge now. Thanks!

**Pull request merged**
