### PR TITLE
Update jwt.md

### PR DESCRIPTION
**Pull request by Ayad0net**
Clarify JWT token generation

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @Ayad0net 

Thanks. We don't recommend using the utility functions in the `hono/utils/*` directory because it's for an internal use-case.

But we are planing to create JWT helpers.

https://github.com/honojs/hono/issues/1443

If this is released, we can update this page.

**Comment by Ayad0net** [comment]
Thanks

**Comment by julianpoma** [comment]
Hi @Ayad0net ! @yusukebe just merged https://github.com/honojs/hono/pull/1472

So you may want to update this doc and be ready for the next minor release :)

**Comment by Ayad0net** [comment]
That's awesome

**Comment by yusukebe** [comment]
Hi @Ayad0net 

Thanks for the PR, I have merged the following PR about JWT. But thanks for making the PR. Please do it again.

https://github.com/honojs/website/pull/102

**Pull request closed without merging**
