### PR TITLE
feat: Support vitepress-twoslash

### PR DESCRIPTION
**Pull request by shinGangan**
### 🙋 Description

Support for using `@shikijs/vitepress-twoslash` in documents.
- refl: https://shiki.style/packages/vitepress

#### 📸 Usage and Captured image

````
```ts twoslash
import { Hono } from 'hono'

const app = new Hono()

app.get('/', (c) => {
  return c.text('Hello Hono!')
})

export default app
```
````

show ↓

### ☑️ Checklist
 
- [ ] linked an issue or discussion
- [x] add example

### 📗 Note

I believe there is still some debate on such issues as "should it be displayed on all pages?"
Therefore, this PR focuses on "building the environment."

This PR is for use when “We want to use Twoslash on Hono.dev as well".

### CODE REVIEW

**Comment by shinGangan** [comment]
Hi @yusukebe .

We consider this PR to be a very low priority for review.
Therefore, we would appreciate a review when you are available. 🙇

**Comment by yusukebe** [comment]
Hi @shinGangan 

This is a super cool feature!!

In Hono, however, we must consider whether to introduce it. This is because the types in Hono are so complex that users often do not immediately understand them when they see them.

For example, the `HandlerInterface` has more than 20 overloads.

Screenshot 2024-02-24 at 22 32 37

So, I am not sure if this is for the benefit of the real users. However, it is an awesome cool feature, so let's leave this PR open.

Thanks!

**Comment by shinGangan** [comment]
> In Hono, however, we must consider whether to introduce it.

I agree with you on this.
The same reason we have not made any updates to the documentation within this PR.

Whether this feature is really necessary for Hono and Hono users needs to be scrutinized within the team.

**Comment by yusukebe** [comment]
@shinGangan 

Thank! Closed. Let's continue in #503 .

**Pull request closed without merging**
